---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ambassador-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: edge-stack
      sourceRef:
        kind: HelmRepository
        name: ambassador
      version: 7.3.2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: ambassador
  targetNamespace: ambassador
  interval: 1m0s
  values:
    replicaCount: 2
    resources:
      limits:
        cpu: 1000m
        memory: 600Mi
      requests:
        cpu: 200m
        memory: 200Mi
